### PR TITLE
Add chunkSize to more efficiently display cards

### PR DESCRIPTION
**Pull request by andiskim**
Awesome package! I had 70+ cards which was causing the Swiper to lag, so I only display {chunkSize} cards at a time

### CODE REVIEW

**Comment by Skipperlla** [comment]
@andiskim There are new improvements and bug fixes that I will add over the weekend and I'm adding this alongside them

**Comment by Skipperlla** [comment]
can you add a description of this feature to the readme?

**Comment by andiskim** [comment]
> can you add a description of this feature to the readme?

done

**Comment by Skipperlla** [comment]
Hi, I tested your code but it doesn't work exactly right, at first I slide 3 cards and the others are not loaded, can you commit this problem again after I fixed the test? @andiskim

**Comment by Skipperlla** [comment]
I'll work on a separate branch for this feature and I'll update you on the progress.

**Pull request closed without merging**
